baseURL = "https://gossis.mit.edu"
languageCode = "en-us"
title = "GOSSIS: Global Open Source Severity of Illness Score: International Benchmarking for Critical Care"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "News"
        url     = "/news"
        weight  = 3
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/gossis_logo2.PNG"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Airspace Hugo theme"
    author = "Themefisher"
    # Google Analitycs
    googleAnalitycsID = "UA-87592301-6"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/gossis1.png"
        heading = "Global Open Source Severity of Illness Score"
        description = "The Global Open Source Severity of Illness Score (GOSSIS) is a new in-hospital mortality prediction algorithm created by the GOSSIS consortium."
        #btn     = true
        #btnText = "Download More"
        #btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "Global"
        [[params.banner.flipText]]
            title   = "Open"
        [[params.banner.flipText]]
            title   = "Free"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT GOSSIS"
        content = "The <b>Global Open Source Severity of Illness Score (GOSSIS)</b> is a new in-hospital mortality prediction algorithm created by the GOSSIS consortium.<br><br> Presently there are consortium members from Argentina (SATIQ),  Australia and New Zealand (ANZICS-APD), Bangladesh, India, Nepal and Sri Lanka (NICST), Brazil (ORCHESTRA), and the United States (eICU-CRD and MIMIC-III)."
        image   = "images/about/gossis_map.png"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "Find out more."
        content = "Use GOSSIS. Contribute data.  Become Part of the Community"
        btnText = "Contact Us"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Feature Product Section
    [params.featureProduct]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

